spring:
  application:
    name: subtitle-translate
  ai:
    openai:
      api-key: lm-studio
      base-url: http://localhost:1234
      chat:
        options:
          stream-usage: false
          #          model: google/gemma-3-12b
          temperature: 1.0
          max_tokens: 500

server:
  port: 8092

logging:
  level:
    org:
      springframework:
        ai: DEBUG

prompt:
  add-to-system: ""

output:
  replace-string: ""

languages:
  input: "Japanese"
  output: "English"

directories:
  input: ""
  output: ""

